// automatically generated by the FlatBuffers compiler, do not modify

package e6.flatbuffers.addressChunk;

@SuppressWarnings("unused")
public final class Vector {
  private Vector() { }
  public static final byte NONE = 0;
  public static final byte Int64Vector = 1;
  public static final byte Int32Vector = 2;

  public static final String[] names = { "NONE", "Int64Vector", "Int32Vector", };

  public static String name(int e) { return names[e]; }
}

